monhanpy/monhan/urls.py
from django.conf.urls import url
from monhan import views

urlpatterns = [
    # 防具
    url(r'^$', views.index, name='index'),
    url(r'^armor/$', views.armor_list, name='armor_list'),
    url(r'^skill/$', views.skill_list, name='skill_list'),
    url(r'^item/$', views.item_list, name='item_list'),
    url(r'^search_armors$', views.search_armors, name='search_armors'),
    url(r'^coodinate_armor_set$', views.coodinate_armor_set, name='coodinate_armor_set'),
]

monhanpy/monhanxx/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^monhan/', include('monhan.urls', namespace='monhan')),
]

monhanpy/monhan/models.py
from django.db.models import Q, Prefetch 
from django.db import models

# TODO: ふたつのスキルを兼ねたスキルの扱い
# TODO: 防御力を数値型にする

# スキル系統というよりも、スキルのベース
# 27|回復速度
class SkillSystem(models.Model):
    """スキル系統"""
    class Meta:
        db_table = 'skill_system'

    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=256)
    # armorseriesskillpoint_set
    # armorskillpoint_set
    # skill_set

# 36|回復速度+2|15|体力ゲージの赤い部分を通常の4倍の速度で回復できる。|27
# 37|回復速度+1|10|体力ゲージの赤い部分を通常の2倍の速度で回復できる。|27
# 38|回復速度-1|-10|体力ゲージの赤い部分の回復速度が通常の1/2になる。|27
# 39|回復速度-2|-15|体力ゲージの赤い部分の回復速度が通常の1/4になる。|27
class Skill(models.Model):
    """スキル"""
    class Meta:
        db_table = 'skill'

    id = models.IntegerField(primary_key=True)
    skill_system = models.ForeignKey(SkillSystem)
    name = models.CharField(max_length=256)
    require_point = models.IntegerField()
    description = models.CharField(max_length=1024)
    # armorseries_set

class Item(models.Model):
    """アイテム"""
    class Meta:
        db_table = 'item'

    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=256)

class ArmorSeries(models.Model):
    """防具"""
    class Meta:
        db_table = 'armor_series'

    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=256)
    rare = models.CharField(max_length=32)
    initial_defense = models.CharField(max_length=16)
    max_defense = models.CharField(max_length=16)
    slot = models.IntegerField()
    fire_resistance = models.IntegerField()
    water_resistance = models.IntegerField()
    thunder_resistance = models.IntegerField()
    ice_resistance = models.IntegerField()
    dragon_resistance = models.IntegerField()
    # armor_set(foreign keyの逆参照)
    skills = models.ManyToManyField(Skill)
    # armorseriesskillpoint_set(foreign keyの逆参照)


class ArmorSeriesSkillPoint(models.Model):
    """防具シリーズスキルポイント"""
    class Meta:
        db_table = 'armor_series_skill_point'

    armor_series = models.ForeignKey(ArmorSeries)
    skill_system = models.ForeignKey(SkillSystem)
    point = models.IntegerField()


class Armor(models.Model):
    """防具"""
    class Meta:
        db_table = 'armor'

    id = models.IntegerField(primary_key=True)
    han_type = models.IntegerField()
    armor_series = models.ForeignKey(ArmorSeries)
    type = models.CharField(max_length=32)
    name = models.CharField(max_length=256)
    slot = models.IntegerField()
    initial_defense = models.CharField(max_length=16)
    max_defense = models.CharField(max_length=16)
    fire_resistance = models.IntegerField()
    water_resistance = models.IntegerField()
    thunder_resistance = models.IntegerField()
    ice_resistance = models.IntegerField()
    dragon_resistance = models.IntegerField()
    # armorskillpoint_set(foreign keyの逆参照)

    def skill_point(self, skill_id):
        point = 0
        for skill_point in self.armorskillpoint_set.filter(Q(skill_system__skill__id=skill_id)).iterator():
            point = point + skill_point.point
        return point

    def skill_system_point(self, skill_system_id):
        point = 0
        for skill_point in self.armorskillpoint_set.filter(Q(skill_system__id=skill_system_id)).iterator():
            point = point + skill_point.point
        return point

# select * from armor_skill_point inner join skill_system on armor_skill_point.skill_system_id = skill_system.id inner join armor on armor_skill_point.armor_id = armor.id where skill_system.name like '%回復速度%';
# 25673|5|15246|27|27|回復速度|15246|頭|フルフルXキャップ|1|64|G級91|-4|1|5|2|1|1030|2
# 25676|2|15247|27|27|回復速度|15247|胴|フルフルXレジスト|0|64|G級91|-4|1|5|2|1|1030|2
# 25679|4|15248|27|27|回復速度|15248|腕|フルフルXガード|2|64|G級91|-4|1|5|2|1|1030|2
# 25683|4|15250|27|27|回復速度|15250|脚|フルフルXレギンス|1|64|G級91|-4|1|5|2|1|1030|2
# 25688|6|15262|27|27|回復速度|15262|胴|フルフルXRレジスト|1|61|G級88|-4|1|5|2|1|1031|2
# 25692|5|15264|27|27|回復速度|15264|腰|フルフルXRコート|2|61|G級88|-4|1|5|2|1|1031|2
# 25695|8|15265|27|27|回復速度|15265|脚|フルフルXRレギンス|1|61|G級88|-4|1|5|2|1|1031|2
# 27594|3|17301|27|27|回復速度|17301|頭|屍装甲・真【頭骨】|2|75|G級99|-1|-1|-1|-1|-1|1169|2
# 27598|3|17302|27|27|回復速度|17302|胴|屍装甲・真【胸骨】|1|75|G級99|-1|-1|-1|-1|-1|1169|2
# 27602|3|17303|27|27|回復速度|17303|腕|屍装甲・真【上腕骨】|1|75|G級99|-1|-1|-1|-1|-1|1169|2
# 27606|3|17304|27|27|回復速度|17304|腰|屍装甲・真【腰骨】|2|75|G級99|-1|-1|-1|-1|-1|1169|2
# 27610|3|17305|27|27|回復速度|17305|脚|屍装甲・真【大腿骨】|1|75|G級99|-1|-1|-1|-1|-1|1169|2
class ArmorSkillPoint(models.Model):
    """防具スキルポイント"""
    class Meta:
        db_table = 'armor_skill_point'

    armor = models.ForeignKey(Armor)
    skill_system = models.ForeignKey(SkillSystem)
    point = models.IntegerField()

monhanpy/monhan/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from django.db.models import Q, Prefetch
from monhan.models import *
from monhan.logic import *

def index(request):
    """トップメニュー"""
    return render(request, 'monhan/index.html')

def armor_list(request):
    """防具一覧"""
    # FIXME: SQLite3だとクエリパラメータが999までしか使えない
    armor_series = ArmorSeries.objects.all().select_related().order_by('id')
#    armor_series = ArmorSeries.objects.all().prefetch_related('armor_set').select_related().order_by('id')
#    armor_series = ArmorSeries.objects.all().prefetch_related('armor_set', 'armor_set__armorskillpoint_set', 'armor_set__armorskillpoint_set__skill_system', 'armor_set__armorskillpoint_set__skill_system__skill_set', 'skills', 'armorseriesskillpoint_set', 'armorseriesskillpoint_set__skill_system').select_related().order_by('id')
#    armor_series = armor_series[:100]
    return render(request, 'monhan/armor_list.html', {'armor_series': armor_series})

def skill_list(request):
    """スキル一覧"""
    skills = Skill.objects.all().order_by('id')
    return render(request, 'monhan/skill_list.html', {'skills': skills})

def item_list(request):
    """アイテム一覧"""
    items = Item.objects.all().order_by('id')
    return render(request, 'monhan/item_list.html', {'items': items})

class SearchArmorsForm(forms.Form):
    """防具検索フォーム"""
    HAN_TYPE_KEYS = [
            (1, '剣士'),
            (2, 'ガンナー')]

    SORT_KEYS = [
            ('id', 'なし',),
            ('initial_defense', '初期防御力',),
            ('max_defense', '最大防御力',),
            ('slot', 'スロット数',)]

    han_type = forms.ChoiceField(label="タイプ", choices=HAN_TYPE_KEYS, initial=1, widget=forms.Select, required=True)
    skill_name = forms.CharField(max_length=32, label="スキル名", required=False)
    skill_system_name = forms.CharField(max_length=32, label="スキル系統", required=False)
    skill_point = forms.IntegerField(label="ポイント数", required=False)
    min_slot = forms.IntegerField(label="最小スロット", required=False)
    initial_defense = forms.IntegerField(label="最小初期防御力", required=False)
    max_defense = forms.IntegerField(label="最小最大防御力", required=False)
    sort_key = forms.ChoiceField(label="並び替", choices=SORT_KEYS, initial='id', widget=forms.Select, required=True)

def search_armors(request):
    """スキルから防具を検索"""
    if request.method == 'POST':
        form = SearchArmorsForm(request.POST)
        if form.is_valid():
            han_type = form.cleaned_data['han_type']
            skill_name = form.cleaned_data['skill_name']
            skill_system_name = form.cleaned_data['skill_system_name']
            skill_point = form.cleaned_data['skill_point']
            min_slot = form.cleaned_data['min_slot']
            initial_defense = form.cleaned_data['initial_defense']
            max_defense = form.cleaned_data['max_defense']
            sort_key = form.cleaned_data['sort_key']
            print(sort_key)

            cond = []
            if han_type != None:
                cond.append(Q(han_type=han_type))
            if skill_name != None and len(skill_name) > 0:
                cond.append(Q(armorskillpoint__skill_system__skill__name__contains=skill_name))
            if skill_system_name != None and len(skill_system_name) > 0:
                cond.append(Q(armorskillpoint__skill_system__name__contains=skill_system_name))
            if skill_point != None:
                cond.append(Q(armorskillpoint__point__gte=skill_point))
            if min_slot != None:
                cond.append(Q(slot__gte=min_slot))
            if initial_defense != None:
                cond.append(Q(initial_defense__gte=initial_defense))
            if max_defense != None:
                cond.append(Q(max_defense__gte=max_defense))

            armors = None
            print(cond)
            # FIXME: SQLite3だとクエリパラメータが999までしか使えない
            if (len(cond) > 0):
                armors = Armor.objects.prefetch_related('armorskillpoint_set', 'armorskillpoint_set__skill_system', 'armorskillpoint_set__skill_system__skill_set').select_related().filter(*cond)
            else:
                armors = Armor.objects.prefetch_related('armorskillpoint_set', 'armorskillpoint_set__skill_system', 'armorskillpoint_set__skill_system__skill_set').select_related().all()
            if sort_key == 'id':
                armors = armors.order_by(sort_key)[:999]
            else:
                armors = armors.order_by(sort_key).reverse()[:999]
            count = armors.count()
            print(count)

            # INNER JOINの重複を弾く
            ids = set([])
            armors2 = []
            for armor in armors:
                if not (armor.id in ids):
                    ids.add(armor.id)
                    armors2.append(armor)

            return render(request, 'monhan/search_armors_result.html',
                    {'armors': armors2, 'armors_length': count, 'form': form})
    else:
        form = SearchArmorsForm()
        return render(request, 'monhan/search_armors.html', {'form': form})

class SkillModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, skill):
        return skill.name

class CoodinateArmorSetForm(forms.Form):
    """防具提案フォーム"""
    HAN_TYPE_KEYS = [
            (1, '剣士'),
            (2, 'ガンナー')]

    han_type = forms.ChoiceField(label="タイプ", choices=HAN_TYPE_KEYS, initial=1, widget=forms.Select, required=True)
    skill1 = SkillModelChoiceField(label="発動スキル1", queryset=Skill.objects.all(), widget=forms.Select, required=False)
    skill2 = SkillModelChoiceField(label="発動スキル2", queryset=Skill.objects.all(), widget=forms.Select, required=False)
    skill3 = SkillModelChoiceField(label="発動スキル3", queryset=Skill.objects.all(), widget=forms.Select, required=False)
    skill_system1 = SkillModelChoiceField(label="スキル系統1", queryset=SkillSystem.objects.all(), widget=forms.Select, required=False)
    skill_point1 = forms.IntegerField(label="スキルポイント1", required=False)
    skill_system2 = SkillModelChoiceField(label="スキル系統2", queryset=SkillSystem.objects.all(), widget=forms.Select, required=False)
    skill_point2 = forms.IntegerField(label="スキルポイント2", required=False)
    skill_system3 = SkillModelChoiceField(label="スキル系統3", queryset=SkillSystem.objects.all(), widget=forms.Select, required=False)
    skill_point3 = forms.IntegerField(label="スキルポイント3", required=False)
    min_slot = forms.IntegerField(label="最小スロット", required=False)
    initial_defense = forms.IntegerField(label="最小初期防御力", required=False)
    max_defense = forms.IntegerField(label="最小最大防御力", required=False)

# スキルとポイント(複数)と最低防御力と最低スロット数を指定する
# 頭・胴・腕・腰・脚を1つずつ選ん防具セットを一覧にし防御力順に表示
def coodinate_armor_set(request):
    """条件から良い防具のセットを捜す"""
    if request.method == 'POST':
        form = CoodinateArmorSetForm(request.POST)
        if form.is_valid():
            han_type = form.cleaned_data['han_type']
            # これらのスキルが発動する
            skill1 = form.cleaned_data['skill1']
            skill2 = form.cleaned_data['skill2']
            skill3 = form.cleaned_data['skill3']
            # スキルポイントが最低これだけある
            skill_system1 = form.cleaned_data['skill_system1']
            skill_point1 = form.cleaned_data['skill_point1']
            skill_system2 = form.cleaned_data['skill_system2']
            skill_point2 = form.cleaned_data['skill_point2']
            skill_system3 = form.cleaned_data['skill_system3']
            skill_point3 = form.cleaned_data['skill_point3']
            # その他条件
            min_slot = form.cleaned_data['min_slot']
            initial_defense = form.cleaned_data['initial_defense']
            max_defense = form.cleaned_data['max_defense']

            # ロジック
            armor_sets = Logic.coodinate_armor_set(
                    han_type,
                    [skill1, skill2, skill3],
                    [(skill_system1, skill_point1), (skill_system2, skill_point2), (skill_system3, skill_point3)],
                    min_slot, (initial_defense, max_defense))

            count = len(armor_sets)
            return render(request, 'monhan/coodinate_armor_set_result.html',
                    {'armor_sets': armor_sets, 'armor_set_length': count, 'form': form})
    else:
        form = CoodinateArmorSetForm()
        return render(request, 'monhan/coodinate_armor_set.html', {'form': form})

monhanpy/monhan/templates/monhan/armor_list.html
{% extends "base.html" %}
{% load filter %}

{% block title %}防具の一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <h2 class="page-header">防具の一覧</h3>
      {% for armor_s in armor_series %}
        <h3>{{ armor_s.name }}</h3>
        <div class="table-responsive">
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>ID</th>
                <th>防具シリーズ名</th>
                <th>初期防御力</th>
                <th>最大防御力</th>
                <th>スロット</th>
                <th>発動スキル</th>
                <th>合計スキルポイント</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{{ armor_s.id }}</td>
                <td>{{ armor_s.name }}</td>
                <td>{{ armor_s.initial_defense }}</td>
                <td>{{ armor_s.max_defense }}</td>
                <td>{{ armor_s.slot }}</td>
                <td>
                  {% for skill in armor_s.skills.all %}
                    {{ skill.name }}<br />
                  {% endfor %}
                </td>
                <td>
                  {% for skill_point in armor_s.armorseriesskillpoint_set.all %}
                    {{ skill_point.skill_system.name }}+{{ skill_point.point }}<br />
                  {% endfor %}
                </td>
              </tr>
            </tbody>
          </table>
        </div> <!-- /.table-responsive -->
        <div class="table-responsive">
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>通番</th>
                <th>ID</th>
                <th>種別</th>
                <th>部位</th>
                <th>防具名</th>
                <th>初期防御力</th>
                <th>最大防御力</th>
                <th>スロット</th>
                <th>スキルポイント</th>
              </tr>
            </thead>
            <tbody>
              {% for armor in armor_s.armor_set.all %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ armor.id }}</td>
                <td>{{ armor.han_type|han_type_name }}</td>
                <td>{{ armor.type }}</td>
                <td>{{ armor.name }}</td>
                <td>{{ armor.initial_defense }}</td>
                <td>{{ armor.max_defense }}</td>
                <td>{{ armor.slot }}</td>
                <td>
                  {% for skill_point in armor.armorskillpoint_set.all %}
                    {{ skill_point.skill_system.name }}+{{ skill_point.point }}<br />
                  {% endfor %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div> <!-- /.table-responsive -->
      {% endfor %}
    </div> <!-- /.col-sm-12 -->
  </div> <!-- /.row -->
{% endblock content %}

monhanpy/monhan/templates/monhan/coodinate_armor_set.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}最適防具検索{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <h2 class="page-header">最適防具検索</h3>
      <form action="{% url 'monhan:coodinate_armor_set' %}" method="POST">{% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-default btn-sm" type="submit" value="検索" />
      </form>
    </div> <!-- /.col-sm-12 -->
  </div> <!-- /.row -->
{% endblock content %}

monhanpy/monhan/templates/monhan/coodinate_armor_set_result.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load filter %}

{% block title %}最適防具検索{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <h2 class="page-header">最適防具検索</h3>
      <form action="{% url 'monhan:coodinate_armor_set' %}" method="POST">{% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-default btn-sm" type="submit" value="検索" />
      </form>
    </div> <!-- /.col-sm-12 -->
  </div> <!-- /.row -->
  <div class="row">
    <div class="col-sm-12">
      検索結果{{ armor_set_length }}件。
      {% if armor_set_length > 1000 %}
        <br />最初の1000件のみ表示します。
      {% endif %}
      <div class="table-responsive">
        {% for armor_set in armor_sets %}
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>通番</th>
                <th>ID</th>
                <th>種別</th>
                <th>部位</th>
                <th>防具名</th>
                <th>初期防御力</th>
                <th>最大防御力</th>
                <th>スロット</th>
                <th>発動スキル</th>
                <th>スキルポイント</th>
              </tr>
            </thead>
            <tbody>
            {% for armor in armor_set %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ armor.id }}</td>
                <td>{{ armor.han_type|han_type_name }}</td>
                <td>{{ armor.type }}</td>
                <td>{{ armor.name }}</td>
                <td>{{ armor.initial_defense }}</td>
                <td>{{ armor.max_defense }}</td>
                <td>{{ armor.slot }}</td>
                <td>
                  # TODO: 発動するスキルのみに限定する
                  # TODO: ここからは削って、タイトルにこのセットで発動するスキル
                  {% for skill_point in armor.armorskillpoint_set.all %}
                    {% for skill in skill_point.skill_system.skill_set.all %}
                      {{ skill.name }}<br />
                    {% endfor %}
                  {% endfor %}
                </td>
                <td>
                  {% for skill_point in armor.armorskillpoint_set.all %}
                    {{ skill_point.skill_system.name }}+{{ skill_point.point }}<br />
                  {% endfor %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        {% endfor %}
      </div> <!-- /.table-responsive -->
    </div> <!-- ./col-sm-12 -->
  </div> <!-- /.row -->
{% endblock content %}

monhanpy/monhan/templates/monhan/index.html
{% extends "base.html" %}

{% block title %}モンハン攻略アプリ{% endblock title %}

{% block extrahead %}
{% endblock %}

{% block content %}
  <h3 class="page-header">メニュー</h3>
  <a href="{% url 'monhan:search_armors' %}" class="btn btn-default btn-sm">防具検索</a>
{% endblock content %}

monhanpy/monhan/templates/monhan/item_list.html
{% extends "base.html" %}
{% load filter %}

{% block title %}アイテムの一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <h2 class="page-header">アイテムの一覧</h3>
      <div class="table-responsive">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>アイテム名</th>
            </tr>
          </thead>
          <tbody>
            {% for item in items %}
            <tr>
              <td>{{ item.id }}</td>
              <td>{{ item.name }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div> <!-- /.table-responsive -->
    </div> <!-- /.col-sm-12 -->
  </div> <!-- /.row -->
{% endblock content %}

monhanpy/monhan/templates/monhan/search_armors.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}防具検索{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <h2 class="page-header">防具検索</h3>
      <form action="{% url 'monhan:search_armors' %}" method="POST">{% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-default btn-sm" type="submit" value="検索" />
      </form>
    </div> <!-- /.col-sm-12 -->
  </div> <!-- /.row -->
{% endblock content %}

monhanpy/monhan/templates/monhan/search_armors_result.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load filter %}

{% block title %}防具検索{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <h2 class="page-header">防具検索</h3>
      <form action="{% url 'monhan:search_armors' %}" method="POST">{% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-default btn-sm" type="submit" value="検索" />
      </form>
    </div> <!-- /.col-sm-12 -->
  </div> <!-- /.row -->
  <div class="row">
    <div class="col-sm-12">
      検索結果{{ armors_length }}件。
      {% if armors_length > 1000 %}
        <br />最初の1000件のみ表示します。
      {% endif %}
      <div class="table-responsive">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>通番</th>
              <th>ID</th>
              <th>種別</th>
              <th>部位</th>
              <th>防具名</th>
              <th>初期防御力</th>
              <th>最大防御力</th>
              <th>スロット</th>
              <th>スキル</th>
              <th>スキルポイント</th>
            </tr>
          </thead>
          <tbody>
          {% for armor in armors %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ armor.id }}</td>
              <td>{{ armor.han_type|han_type_name }}</td>
              <td>{{ armor.type }}</td>
              <td>{{ armor.name }}</td>
              <td>{{ armor.initial_defense }}</td>
              <td>{{ armor.max_defense }}</td>
              <td>{{ armor.slot }}</td>
              <td>
                {% for skill_point in armor.armorskillpoint_set.all %}
                  {% for skill in skill_point.skill_system.skill_set.all %}
                    {{ skill.name }}<br />
                  {% endfor %}
                {% endfor %}
              </td>
              <td>
                {% for skill_point in armor.armorskillpoint_set.all %}
                  {{ skill_point.skill_system.name }}+{{ skill_point.point }}<br />
                {% endfor %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div> <!-- /.table-responsive -->
    </div> <!-- ./col-sm-12 -->
  </div> <!-- /.row -->
{% endblock content %}

monhanpy/monhan/templates/monhan/skill_list.html
{% extends "base.html" %}
{% load filter %}

{% block title %}スキルの一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <h2 class="page-header">スキルの一覧</h3>
      <div class="table-responsive">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>発動スキル</th>
              <th>スキルポイント</th>
              <th>説明</th>
            </tr>
          </thead>
          <tbody>
            {% for skill in skills %}
            <tr>
              <td>{{ skill.id }}</td>
              <td>{{ skill.name }}</td>
              <td>{{ skill|skill_point }}</td>
              <td>{{ skill.description }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div> <!-- /.table-responsive -->
    </div> <!-- /.col-sm-12 -->
  </div> <!-- /.row -->
{% endblock content %}